name: hpi_russell
description: "A Project by Ruxzom"
 
publish_to: 'none' 

 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

 
dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.0
  icons_launcher: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.0


flutter_native_splash:
  image: assets/logo.jpg
  color: "#27AE51"
  android_gravity: center
  ios_content_mode: center 
  android: true
  ios: true 

icons_launcher:
  image_path: "assets/logo.jpg"
  platforms:
   android:
    enable: true
  ios:
    enable: true
 
flutter:

 
  uses-material-design: true

 
  assets:
    - assets/logo.jpg
 
 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 